server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/care_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: localhost
      port: 6379
      password: qwer1234
      repositories:
        enabled: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: "9E6436E6EB6D3B111EBFC58691E53aaaaaaaaaaaaaaaabbbbb"
  default:
    admin_id: supercoding
    admin_pwd: admin1234

  aes:
    secret: "qrWkovCNhAToTFwnSMXXsy9aSfEOt9G2"


springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  packages-to-scan: com.github.backend.web.controller
  api-docs:
    path: /api-docs




logging:
  config: classpath:logback-spring-local.xml
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucketName:
    region:
      static:
    stack:
      auto: