server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

  datasource:
    url: jdbc:mariadb://database-1.chegyyioe8xx.ap-northeast-2.rds.amazonaws.com:3306/care_service?useUnicode=true&characterEncoding=UTF-8
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    repositories:
      bootstrap-mode: deferred

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false

  jwt:
    secret: ${JWT_SECRET}
  default:
    admin_id: supercoding
    admin_pwd: admin1234

  aes:
    secret: ${AES_KEY}

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  packages-to-scan: com.github.backend.web.controller
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback-spring-prod.xml
cloud:
  aws:
    credentials:
      access-key: ${CLOUD_S3_ACCESS_KEY}
      secret-key: ${CLOUD_S3_SECRET_KEY}
    s3:
      bucketName: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

message:
  apikey: ${COOLSMS_APIKEY}
  api-secret: ${COOLSMS_APISECRET}
  phone-num: ${COOLSMS_PHONENUMBER}